export const MUSCLE_GROUPS = ['Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps', 'Forearms', 'Legs', 'Core'];

/**
 * Form notes that have since been rewritten, keyed by exercise id and holding
 * the exact superseded text.
 *
 * Prescription that the app now derives and displays itself — rep ranges, RIR,
 * set counts — reads as duplication sitting in a form-cue field, so it gets
 * retired here. Only a copy still byte-identical to this is replaced, so notes
 * edited by hand are left alone.
 */
export const SUPERSEDED_NOTES = {
    'flat-dumbbell-press':
        'Press dumbbells up and slightly together at the top. Lower with control to chest level, keeping wrists stacked over elbows. Stay in the 8-12 rep range with a controlled tempo.',
};

export const EQUIPMENT = ['Barbell', 'Dumbbell', 'Cable Machine', 'Bodyweight', 'Machine', 'Kettlebell', 'Bands'];

// ORV's 5-Day Gym Routine (Upper/Lower/Push/Pull/Legs+Arms) — every movement
// named across the plan, deduped, with "X or Y" alternatives split into
// separate entries so each can be logged on its own.
export const DEFAULT_EXERCISES = [
    // --- Chest -------------------------------------------------------------
    {
        id: 'barbell-bench-press',
        name: 'Barbell Bench Press',
        muscleGroup: 'Chest',
        equipment: 'Barbell',
        attachment: 'Flat bench, straight bar',
        notes: 'Lie flat on the bench with feet firmly on the ground. Lower the bar to mid-chest and press explosively. Keep core tight and avoid bouncing.',
    },
    {
        id: 'incline-dumbbell-press',
        name: 'Incline Dumbbell Press',
        muscleGroup: 'Chest',
        equipment: 'Dumbbell',
        attachment: 'Bench at 30–45°',
        notes: 'Set the bench to a 30-45 degree incline. Press dumbbells up and slightly together without locking out hard. Lower with control to the top of the chest.',
    },
    {
        id: 'flat-dumbbell-press',
        name: 'Flat Dumbbell Bench Press',
        muscleGroup: 'Chest',
        equipment: 'Dumbbell',
        attachment: 'Flat bench',
        notes: 'Press dumbbells up and slightly together at the top. Lower with control to chest level, keeping wrists stacked over elbows. Keep the tempo controlled rather than bouncing out of the bottom.',
    },
    {
        id: 'cable-chest-fly',
        name: 'Cable Fly',
        muscleGroup: 'Chest',
        equipment: 'Cable Machine',
        attachment: 'Two D-handles, pulleys at chest height',
        notes: 'Stand in the middle with a slight bend in the elbows. Bring the handles together in a smooth arc, squeezing the chest at the finish. Control the stretch on the way back.',
    },
    {
        id: 'pec-deck-fly',
        name: 'Pec Deck Fly',
        muscleGroup: 'Chest',
        equipment: 'Machine',
        attachment: '',
        notes: 'Adjust the seat so the handles sit at chest height. Bring the pads together in front of the chest without shrugging. Control the return to a full stretch.',
    },
    {
        id: 'machine-chest-press',
        name: 'Machine Chest Press',
        muscleGroup: 'Chest',
        equipment: 'Machine',
        attachment: 'Seat set so the handles are at mid-chest',
        notes: 'Set the seat so the handles sit level with the mid-chest. Press forward without locking out hard, then return slowly until you feel a stretch across the chest.',
    },
    {
        id: 'push-up',
        name: 'Push-Up',
        muscleGroup: 'Chest',
        equipment: 'Bodyweight',
        attachment: '',
        notes: 'Hands slightly wider than the shoulders, body in a straight line from head to heels. Lower the chest to just above the floor and press back up. Elevate the feet or add a plate for more load.',
    },
    {
        id: 'dumbbell-fly',
        name: 'Dumbbell Fly',
        muscleGroup: 'Chest',
        equipment: 'Dumbbell',
        attachment: 'Flat bench',
        notes: 'Lie on a flat bench with the dumbbells above the chest and a slight bend in the elbows. Open the arms in a wide arc until you feel a deep chest stretch, then bring them back together.',
    },

    // --- Back ----------------------------------------------------------------
    {
        id: 'bodyweight-pull-up',
        name: 'Pull-ups',
        muscleGroup: 'Back',
        equipment: 'Bodyweight',
        attachment: 'Fixed bar, overhand grip',
        notes: 'Grip the bar slightly wider than shoulder width. Pull chest to bar, keeping elbows close. Full range of motion from dead hang to chin over bar.',
    },
    {
        id: 'chest-supported-row',
        name: 'Chest-Supported Row',
        muscleGroup: 'Back',
        equipment: 'Machine',
        attachment: 'Chest-supported row bench',
        notes: "Lie chest-down on the pad so the torso can't swing. Row the handles to your ribs, squeezing the shoulder blades together. Lower with control to a full stretch.",
    },
    {
        id: 'one-arm-dumbbell-row',
        name: 'One-Arm Dumbbell Row',
        muscleGroup: 'Back',
        equipment: 'Dumbbell',
        attachment: 'Flat bench for support',
        notes: 'Brace one hand and knee on a bench, keeping the back flat. Row the dumbbell to the hip, driving the elbow up and back. Lower under control without twisting the torso.',
    },
    {
        id: 'barbell-bent-over-row',
        name: 'Barbell Row',
        muscleGroup: 'Back',
        equipment: 'Barbell',
        attachment: 'Straight bar',
        notes: 'Hinge at the hips with a slight knee bend. Row the bar to the lower chest, keeping the core tight. Retract the shoulder blades and drive the elbows back.',
    },
    {
        id: 'neutral-grip-lat-pulldown',
        name: 'Neutral-Grip Lat Pulldown',
        muscleGroup: 'Back',
        equipment: 'Cable Machine',
        attachment: 'Neutral-grip handle, high pulley',
        notes: 'Pull the handle down to the upper chest with elbows driving down and back. Squeeze the lats at the bottom. Control the weight back up to a full stretch.',
    },
    {
        id: 'reverse-pec-deck',
        name: 'Reverse Pec Deck',
        muscleGroup: 'Back',
        equipment: 'Machine',
        attachment: 'Pec deck, reverse-fly position',
        notes: 'Face into the pad with arms out in front. Pull the handles out and back, squeezing the rear delts and upper back. Keep the movement slow and controlled.',
    },
    {
        id: 'chin-up',
        name: 'Chin-Ups',
        muscleGroup: 'Back',
        equipment: 'Bodyweight',
        attachment: 'Fixed bar, underhand grip',
        notes: 'Underhand grip about shoulder-width. Pull the chest toward the bar by driving the elbows down. Lower to a full hang under control.',
    },
    {
        id: 'assisted-pull-up-machine',
        name: 'Assisted Pull-Up Machine',
        muscleGroup: 'Back',
        equipment: 'Machine',
        attachment: 'Assisted pull-up machine',
        notes: 'Set the assistance so you can hit your reps with good form. Pull the chest toward the handles and lower to a full stretch. Reduce the assistance as you get stronger.',
    },
    {
        id: 'seated-cable-row',
        name: 'Seated Cable Row',
        muscleGroup: 'Back',
        equipment: 'Cable Machine',
        attachment: 'Close-grip handle, low pulley',
        notes: 'Sit tall with a slight bend in the knees. Pull the handle to the lower ribs and squeeze the shoulder blades together. Let the shoulders stretch forward under control.',
    },
    {
        id: 'face-pull',
        name: 'Face Pull',
        muscleGroup: 'Back',
        equipment: 'Cable Machine',
        attachment: 'Rope attachment, high pulley',
        notes: 'Pull the rope toward the face with the elbows high and wide. Finish with the hands beside the ears, squeezing the rear shoulders and upper back. Control the return.',
    },
    {
        id: 'dumbbell-rear-delt-fly',
        name: 'Dumbbell Rear Delt Fly',
        muscleGroup: 'Back',
        equipment: 'Dumbbell',
        attachment: 'Bent over, or chest on an incline bench',
        notes: 'Hinge forward or lie chest-down on an incline bench. With a slight bend in the elbows, raise the dumbbells out to the sides to shoulder height. Lower slowly without swinging.',
    },

    // --- Shoulders -----------------------------------------------------------
    {
        id: 'seated-dumbbell-shoulder-press',
        name: 'Seated Dumbbell Shoulder Press',
        muscleGroup: 'Shoulders',
        equipment: 'Dumbbell',
        attachment: 'Seated bench with back support',
        notes: 'Sit with back supported and press dumbbells overhead in a slight arc. Avoid flaring the elbows out fully at the bottom. Control the descent back to shoulder height.',
    },
    {
        id: 'cable-lateral-raise',
        name: 'Cable Lateral Raise',
        muscleGroup: 'Shoulders',
        equipment: 'Cable Machine',
        attachment: 'Single D-handle, low pulley',
        notes: 'Stand side-on to the pulley and raise the handle out to shoulder height. Keep a slight bend in the elbow throughout. Lower with control rather than dropping the weight.',
    },
    {
        id: 'dumbbell-lateral-raise',
        name: 'Dumbbell Lateral Raise',
        muscleGroup: 'Shoulders',
        equipment: 'Dumbbell',
        attachment: '',
        notes: 'Lift dumbbells out to shoulder height with a slight elbow bend. Keep wrists neutral and lead with the elbows. Raise under control with minimal momentum.',
    },
    {
        id: 'barbell-overhead-press',
        name: 'Barbell Overhead Press',
        muscleGroup: 'Shoulders',
        equipment: 'Barbell',
        attachment: 'Squat rack, straight bar, standing',
        notes: 'Bar at the collarbone with the elbows slightly in front. Squeeze the glutes and press straight up, moving the head back and then through. Lock out over the mid-foot and lower with control.',
    },
    {
        id: 'machine-shoulder-press',
        name: 'Machine Shoulder Press',
        muscleGroup: 'Shoulders',
        equipment: 'Machine',
        attachment: 'Seat set so the handles start at shoulder height',
        notes: 'Set the seat so the handles start level with the shoulders. Press up without shrugging, stopping just short of lockout. Lower slowly to the start.',
    },
    {
        id: 'machine-lateral-raise',
        name: 'Machine Lateral Raise',
        muscleGroup: 'Shoulders',
        equipment: 'Machine',
        attachment: 'Lateral raise machine',
        notes: 'Elbows against the pads, with the seat set so the pivot lines up with the shoulders. Raise the arms out to shoulder height without shrugging. Lower slowly.',
    },

    // --- Biceps ----------------------------------------------------------------
    {
        id: 'ez-bar-curl',
        name: 'EZ-Bar Curl',
        muscleGroup: 'Biceps',
        equipment: 'Barbell',
        attachment: 'EZ bar',
        notes: 'Keep elbows pinned to your sides and curl the bar up under control. Squeeze at the top without swinging the torso. Lower slowly through the full range.',
    },
    {
        id: 'incline-dumbbell-curl',
        name: 'Incline Dumbbell Curl',
        muscleGroup: 'Biceps',
        equipment: 'Dumbbell',
        attachment: 'Incline bench',
        notes: 'Sit back on an incline bench with arms hanging straight down. Curl the dumbbells up without letting the elbows drift forward. Lower slowly to feel a full stretch at the bottom.',
    },
    {
        id: 'preacher-curl',
        name: 'Preacher Curl',
        muscleGroup: 'Biceps',
        equipment: 'Barbell',
        attachment: 'Preacher bench, EZ bar',
        notes: 'Rest the upper arms flat on the preacher pad. Curl the bar up without letting the elbows lift off the pad. Lower under control, stopping just short of full lockout.',
    },
    {
        id: 'dumbbell-hammer-curl',
        name: 'Hammer Curl',
        muscleGroup: 'Biceps',
        equipment: 'Dumbbell',
        attachment: '',
        notes: 'Hold dumbbells with palms facing in and curl without rotating the wrist. Keep elbows tucked to the ribs. Hits the biceps and forearms together.',
    },
    {
        id: 'cable-bicep-curl',
        name: 'Cable Curl',
        muscleGroup: 'Biceps',
        equipment: 'Cable Machine',
        attachment: 'Straight bar, low pulley',
        notes: 'Constant tension on the biceps throughout the set. Keep elbows pinned at your sides. Smooth, controlled movement without swinging.',
    },

    // --- Triceps -----------------------------------------------------------
    {
        id: 'overhead-cable-triceps-extension',
        name: 'Overhead Cable Triceps Extension',
        muscleGroup: 'Triceps',
        equipment: 'Cable Machine',
        attachment: 'Rope attachment, low pulley behind head',
        notes: 'Face away from the pulley and extend the rope overhead. Keep the elbows pointed forward and stationary. Feel a deep stretch at the bottom of each rep.',
    },
    {
        id: 'rope-triceps-pressdown',
        name: 'Rope Triceps Pressdown',
        muscleGroup: 'Triceps',
        equipment: 'Cable Machine',
        attachment: 'Rope attachment, high pulley',
        notes: 'Keep elbows stationary and pinned to your sides. Push the rope down and spread the ends apart at the bottom. Peak contraction at full extension.',
    },
    {
        id: 'single-arm-cable-triceps-extension',
        name: 'Single-Arm Cable Triceps Extension',
        muscleGroup: 'Triceps',
        equipment: 'Cable Machine',
        attachment: 'Single D-handle, high pulley',
        notes: 'Face away from the pulley with the elbow pinned high and close to the head. Extend one arm down and out, keeping the upper arm still. Control the weight back up to a full stretch.',
    },
    {
        id: 'ez-bar-skull-crusher',
        name: 'EZ-Bar Skull Crusher',
        muscleGroup: 'Triceps',
        equipment: 'Barbell',
        attachment: 'Flat bench, EZ bar',
        notes: 'Lie back with the bar over the chest and the elbows pointing at the ceiling. Bend only at the elbows to lower the bar toward the forehead, then extend back up.',
    },
    {
        id: 'close-grip-bench-press',
        name: 'Close-Grip Bench Press',
        muscleGroup: 'Triceps',
        equipment: 'Barbell',
        attachment: 'Flat bench, straight bar',
        notes: 'Hands about shoulder-width apart with the elbows tucked at roughly 45 degrees. Lower to the lower chest and press up, driving through the triceps.',
    },

    // --- Legs ----------------------------------------------------------------
    {
        id: 'barbell-back-squat',
        name: 'Barbell Back Squat',
        muscleGroup: 'Legs',
        equipment: 'Barbell',
        attachment: 'Squat rack, straight bar',
        notes: 'Descend to parallel or below with chest up and knees tracking over toes. Drive through the heels to stand. Keep the core braced throughout.',
    },
    {
        id: 'romanian-deadlift-barbell',
        name: 'Romanian Deadlift',
        muscleGroup: 'Legs',
        equipment: 'Barbell',
        attachment: 'Straight bar, from rack',
        notes: 'Start standing and hinge at the hips with a soft knee bend, sliding the bar down the thighs. Stop when you feel a deep hamstring stretch. Drive the hips forward to stand.',
    },
    {
        id: 'machine-leg-press',
        name: 'Leg Press',
        muscleGroup: 'Legs',
        equipment: 'Machine',
        attachment: '',
        notes: 'Feet shoulder-width apart on the platform. Lower the weight until the knees reach about 90 degrees. Drive through the full foot to extend.',
    },
    {
        id: 'hack-squat',
        name: 'Hack Squat Machine',
        muscleGroup: 'Legs',
        equipment: 'Machine',
        attachment: '',
        notes: 'Set feet shoulder-width on the platform with the back flat against the pad. Descend under control to a comfortable depth. Drive through the whole foot to stand.',
    },
    {
        id: 'goblet-squat',
        name: 'Heel-Elevated Goblet Squat',
        muscleGroup: 'Legs',
        equipment: 'Dumbbell',
        attachment: 'Small plate or wedge under heels',
        notes: 'Hold a dumbbell close to the chest with heels slightly raised. Squat down keeping the torso upright and knees tracking over toes. Use as the hack squat substitute when the machine is unavailable.',
    },
    {
        id: 'machine-leg-extension',
        name: 'Leg Extension',
        muscleGroup: 'Legs',
        equipment: 'Machine',
        attachment: '',
        notes: 'Extend the legs to full knee extension and squeeze the quads. Control the weight on the descent. No jerking or bouncing.',
    },
    {
        id: 'seated-leg-curl',
        name: 'Seated Leg Curl',
        muscleGroup: 'Legs',
        equipment: 'Machine',
        attachment: 'Seated leg curl machine',
        notes: 'Adjust the pad to sit just above the heels. Curl the legs down and squeeze the hamstrings at the bottom. Control the return to a full stretch.',
    },
    {
        id: 'lying-leg-curl',
        name: 'Lying Leg Curl',
        muscleGroup: 'Legs',
        equipment: 'Machine',
        attachment: 'Lying/prone leg curl machine',
        notes: 'Lie face-down with the pad just above the heels. Curl the pad toward the glutes in a controlled manner. Lower with control rather than letting the weight drop.',
    },
    {
        id: 'standing-calf-raise',
        name: 'Standing Calf Raise',
        muscleGroup: 'Legs',
        equipment: 'Machine',
        attachment: '',
        notes: 'Stand tall with the balls of the feet on the platform. Rise onto the toes, pausing briefly at the top. Lower until you feel a deep stretch in the calf.',
    },
    {
        id: 'seated-calf-raise',
        name: 'Seated Calf Raise',
        muscleGroup: 'Legs',
        equipment: 'Machine',
        attachment: '',
        notes: 'Sit with the pad resting just above the knees and the balls of the feet on the platform. Rise onto the toes and pause at the top. Lower slowly for a full stretch.',
    },
    {
        id: 'conventional-deadlift',
        name: 'Conventional Deadlift',
        muscleGroup: 'Legs',
        equipment: 'Barbell',
        attachment: 'Straight bar, from the floor',
        notes: 'Bar over mid-foot, hips back, grip just outside the knees. Brace, push the floor away and keep the bar dragging up the legs. Stand tall, then lower with a flat back.',
    },
    {
        id: 'barbell-front-squat',
        name: 'Barbell Front Squat',
        muscleGroup: 'Legs',
        equipment: 'Barbell',
        attachment: 'Squat rack, straight bar',
        notes: 'Rest the bar on the front of the shoulders with the elbows high. Keep the torso upright and squat to parallel or below. Drive up through the whole foot.',
    },
    {
        id: 'bulgarian-split-squat',
        name: 'Bulgarian Split Squat',
        muscleGroup: 'Legs',
        equipment: 'Dumbbell',
        attachment: 'Bench behind for the back foot',
        notes: 'Rear foot on a bench, front foot far enough forward that the shin stays near vertical. Lower straight down until the front thigh is parallel, then drive up through the front heel.',
    },
    {
        id: 'barbell-hip-thrust',
        name: 'Barbell Hip Thrust',
        muscleGroup: 'Legs',
        equipment: 'Barbell',
        attachment: 'Bench, pad on the bar',
        notes: 'Upper back against a bench with the bar over the hips. Drive the hips up until the torso is level with the thighs, chin tucked. Squeeze the glutes at the top and lower with control.',
    },
    {
        id: 'dumbbell-romanian-deadlift',
        name: 'Dumbbell Romanian Deadlift',
        muscleGroup: 'Legs',
        equipment: 'Dumbbell',
        attachment: '',
        notes: 'Hold dumbbells in front of the thighs and hinge at the hips with a soft bend in the knees. Slide them down the legs to a deep hamstring stretch, then drive the hips forward to stand.',
    },
    {
        id: 'leg-press-calf-raise',
        name: 'Leg Press Calf Raise',
        muscleGroup: 'Legs',
        equipment: 'Machine',
        attachment: 'Leg press, balls of the feet on the platform',
        notes: 'Sit in the leg press with only the balls of the feet on the platform and the legs straight. Lower the heels for a full stretch, then press up as high as you can. Never snap the knees into lockout.',
    },

    // --- Core ----------------------------------------------------------------
    {
        id: 'hanging-knee-raise',
        name: 'Hanging Knee Raise',
        muscleGroup: 'Core',
        equipment: 'Bodyweight',
        attachment: 'Pull-up bar',
        notes: 'Hang from the bar with a slight bend in the elbows. Raise the knees toward the chest using the abs, not momentum. Lower with control back to a dead hang.',
    },
    {
        id: 'cable-crunch',
        name: 'Cable Crunch',
        muscleGroup: 'Core',
        equipment: 'Cable Machine',
        attachment: 'Rope attachment, high pulley',
        notes: 'Hold the rope attachment behind the head and kneel below the pulley. Crunch forward by flexing the abs, driving the elbows toward the hips. Feel the contraction in the upper abs.',
    },
    {
        id: 'ab-wheel-rollout',
        name: 'Ab Wheel Rollout',
        muscleGroup: 'Core',
        equipment: 'Bodyweight',
        attachment: 'Ab wheel',
        notes: 'Kneel with the wheel under the shoulders. Brace the abs, round the lower back slightly and roll out as far as you can without the hips sagging, then pull back in.',
    },
    {
        id: 'decline-sit-up',
        name: 'Decline Sit-Up',
        muscleGroup: 'Core',
        equipment: 'Bodyweight',
        attachment: 'Decline bench',
        notes: 'Hook the feet under the pads with the arms crossed on the chest. Curl up using the abs rather than pulling on the neck, and lower slowly. Hold a plate to add load.',
    },
];
